name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from pack.json
        id: version
        run: |
          VERSION=$(jq -r '.version' pack.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Get changelog for this version
        id: changelog
        run: |
          VERSION=${{ steps.version.outputs.version }}
          CHANGELOG=$(jq -r --arg v "$VERSION" '.[$v][]' changelog.json | sed 's/^/- /')
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create ZIP file
        run: |
          zip -r NovaUi.zip . -x ".git/*"

      - name: Create Extension Zip
        run: |
          mkdir temp_ext

          rsync -av . temp_ext \
            --exclude ".git" \
            --exclude "animate_bg" \
            --exclude "GJ_gradientBG.png.animate.json" \
            --exclude "NovaUi.zip" 

          jq '.name = "Nova Ui: Extension"' temp_ext/pack.json > temp_ext/pack_temp.json
          mv temp_ext/pack_temp.json temp_ext/pack.json

          cd temp_ext
          zip -r ../NovaUi_Extension.zip .
          cd .. 
          rm -rf temp_ext

      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            # ChangeLog
            ${{ steps.changelog.outputs.log }}
          files: |
            NovaUi.zip
            NovaUi_Extension.zip
