name: Update Download Count

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # update tiap 30 menit

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get download data
        id: downloads
        run: |
          DATA=$(curl -s https://api.github.com/repos/DANZGAME-GD/NovaUI/releases)

          NOVAUI=$(echo "$DATA" | jq '[.[].assets[] | select(.name=="NovaUi.zip") | .download_count] | add // 0')
          EXTENSION=$(echo "$DATA" | jq '[.[].assets[] | select(.name=="NovaUi_Extension.zip") | .download_count] | add // 0')

          echo "nova=$NOVAUI" >> $GITHUB_OUTPUT
          echo "ext=$EXTENSION" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i "s/DOWNLOAD_NOVAUI/${{ steps.downloads.outputs.nova }}/g" README.md
          sed -i "s/DOWNLOAD_EXTENSION/${{ steps.downloads.outputs.ext }}/g" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update download count" || echo "No changes"
          git push
